### ISSUE TITLE
Urgent!!Format of documentation 

### ISSUE THREAD

**Issue by yanji1221** [CS2103AUG2017-W10-B4/main#116]
@erik0704 Erik, there are some problems with the format of pdf of documentation, when you store the pdf, you should check the background graphics and uncheck the Header and Footer under option.  Also all hyperlinks are not activated? 
![image](https://user-images.githubusercontent.com/22042886/32725735-2fb94c30-c8b1-11e7-84e2-173e522138e8.png)

**Comment by yanji1221** [comment]
[NeoXPro Manager - Developer Guide.pdf](https://github.com/CS2103AUG2017-W10-B4/main/files/1466827/NeoXPro.Manager.-.Developer.Guide.pdf)
Should be like this, the content pages can link to parts, and links are preserved @erik0704 
But don't use this one, I haven't sync with latest commit.

**Comment by yanji1221** [comment]
@erik0704  follow the instructions under 4.3. Converting Documentation to PDF format:
https://nus-cs2103-ay1718s1.github.io/addressbook-level4/DeveloperGuide.html#documentation

**Comment by yanji1221** [comment]
@erik0704 @quangtdn @hxy0229 anyone there?

**Comment by erik0704** [comment]
resolved
